hdp_api/_router.py, hdp_api/routes/swpMatchmaking.py, hyper_api/variable.py
- `GET /projects/{project_ID}/redeployments/{work_ID}/agents` : listing unmatched agents available for redeployment.
- `/projects/{project_ID}/redeployments/{work_ID}/agents/{agent_ID}` : listing all possible redeployments for a given agent.
=> Port Variable last update and add SWP Matchmaking routes

hyper_api/model.py
In Model class, the create function name contains the name of the model type
=> Fix create function call in get_or_create_hypercube function in Model class

hdp_api/routes/alerts.py
Deletion of the aggregation route (_getAlertsAggregate) that used to get the list of alerts on a dataset, to use an other existing route (_getAlerts).
It was made to simplify the code and be able to use only one path (prevents complications and bugs)
=> Delete aggregation route on alerts

hdp_api/routes/alerts.py, hdp_api/routes/datasetReshapes.py
Alerts and reshapes routes have been updated but the corresponding code wasn't ported. 
- getAlerts (updated) : get all alerts from a group
- computeAlert (removed) : compute a specific alert
- computeAlerts (new) : compute all alerts from a group
- ignoreAlert (new) : ignore a specific alert
- ignoreAlerts (new) : ignore all alerts from a group
- resolveAlert (new) : resolve a specific alert
- proposeAlertResolution (new) : get a proposed transformation based on an alert
- proposeAlertsResolution (new) : get proposed transformation for all alerts from a group
- updateAlert (removed) : update an alert
- proposeAlterations (new) : get a list of empty transformation (update) on a provided list of variables
=> Update Alerts and Reshapes routes with missing changes

hdp_api/routes/reports.py
Add missing route : 
*exportProjectReports*
`GET /projects/{project_ID}/reports?report=report_name`
Export a Project-level error or warning report.
=> Add missing report route

sessionClass.py
The URL string was not well initialized due to **f** missing before **''**
=> Fix url format string for session

hdp_api/_router.py, hdp_api/routes/datasetResources.py
`/projects/{project_ID}/datasets/{dataset_ID}/resources?{handler}={resource_ID}`
This route allows the user to fetch resources that may be generated at a dataset level. 
```
params = {"handler": "resource_ID"}
api.DatasetResources.getdatasetresource(project_ID="project_ID", dataset_ID="dataset_ID", params=params)
```
- 200 Success : Content of the resource
- 403 Not Authorized : Not logged or feature not available for the user
- 500 Error : Unable to access the resource
For security purposes, no details are given on whether the requested project, dataset, resource exists or not.
=> Add route to access Dataset-level resources

hdp_api/routes/nitro.py
`/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/tunes/export`
This route allows the user to get a link to export Tunes from a Forecast.
```
api.DatasetResources.exportforcasttunes/(project_ID="project_ID", dataset_ID="dataset_ID", forecast_ID="forecast_ID")
```
- 200 Success : Return in the body, a json containing the url to download the Forecast Tunes file
- 403 Not Authorized : Not logged or feature not available for the user
- 500 Error : Unable to access the forecast tunes
For security purposes, no details are given on whether the requested project, dataset, forecast exists or not.
=> Change the route to export the tunes of a particular forecast

hdp_api/_router.py, hdp_api/routes/base/resource_base.py, hdp_api/routes/base/route_base.py, hdp_api/routes/base/version_management.py, sessionClass.py
- The version management on the router startup wasn't compatible with current platforms due to a duplicate "/" on the `/about` route. The call has been secured so even a wrong call will not prevent the api from running and the session now checks for duplicate "/" before calls. 
- The `deprecated` route decorator has been renamed `deprecated_since`. The decorator usage remains unchanged. 
- Added the `available_since` decorator. Which has a similar usage to the `deprecated_since` decorator.  If the server version is lower than the route version, the route is not created on the API. 
```
from HyperAPI.hdp_api.routes import Resource, Route, available_since
class System(Resource):
name = "System"
@available_since('4.3')
class _Menu(Route):
name = "Menu"
httpMethod = Route.GET
path = …
```
=> Fix and Update version management

utils/version.py
Updating the version code to handle version labels with "v" prefixes or with a version name instead of major.minor syntax. 
```
Version('4.3-b8da1dbae296964523bf0b86efa039c1679d9a7c').__dict__
{'build': 'b8da1dbae296964523bf0b86efa039c1679d9a7c',
'is_dev': False,
'major': 4,
'minor': 3}
```
```
Version('v4.3-b8da1dbae296964523bf0b86efa039c1679d9a7c').__dict__
{'build': 'b8da1dbae296964523bf0b86efa039c1679d9a7c',
'is_dev': False,
'major': 4,
'minor': 3}
```
```
Version('4.3v-b8da1dbae296964523bf0b86efa039c1679d9a7c').__dict__
{'build': 'b8da1dbae296964523bf0b86efa039c1679d9a7c',
'is_dev': True,
'major': None,
'minor': None}
```
```
Version('master-b8da1dbae296964523bf0b86efa039c1679d9a7c').__dict__
{'build': 'b8da1dbae296964523bf0b86efa039c1679d9a7c',
'is_dev': True,
'major': None, …
```
=> Update Version management to handle CI version

hdp_api/routes/smartViz.py
**Updating route :**
_**1.**_ This route allows the user to get all the smartdataviz for a dataset.
`/projects/{project_ID}/smartDataViz/`
**Usage :**
_**1.**_ `api.SmartDataViz.computesmartdataviz(project_ID="project_ID")`
**Returns :**
_**1.**_  - 201 Success : All SmartDataViz
- 500 Error : SmartDataViz FindAll Failed
=> fixing smartDataViz route

hdp_api/routes/prediction.py, hyper_api/dataset.py, hyper_api/model.py
Add routes for reading or exporting metadata and DiscreteDict used by a previous model to apply on a new dataset whith same encoding.
Add a method in class DatasetFactory for this purpose
Add methods to return preprocessed dataframe for sklearn models
Add methods to export model
=>  Add API methods for scikit-learn exported model utilization

HyperAPI/config.py
Windows users have settings using `
We need to check this character in the config
=> Fix config reading for Windows users

HyperAPI/hyper_api/dataset.py
When encoding a dataframe from an existing dataframe (useful for a scikit model), we want to keep the original variable names.
=> Add option keepVariableName in DatasetFactory

buildspec.yml, package_metadata.json, setup.py
This PR introduces the `PACKAGE_VERSION` variable that defines the generated wheel's version.
This variable has to be set in CodeBuild overrides when triggering a build.
When this variable is not defined, the wheel's version defaults to `999.1-dev`.
=> Build pipeline uses PACKAGE_VERSION variable to set wheel's version

HyperAPI/hdp_api/routes/datasetReshapes.py, HyperAPI/hdp_api/routes/optimProcess.py
Routes (available on hdp version >= 3.3): 
- Publish a Control Chart to the ETL:
`POST /optimProcess/projects/{project_ID}/controlCharts/{controlChart_ID}/etlpublish`
- Publish a Reshape to the ETL
`POST /projects/{project_ID}/reshapes/{reshape_ID}/etlpublish`
=> Add publish to ETL routes for Control Charts and Reshapes

HyperAPI/hdp_api/routes/nitro.py, changelog.md
Routes (available on hdp version >= 3.5): 
- get Forecast Tunes Stats to Nitro routes for ForecastTunes:
`POST /nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/tunes/stats`
=> [5.1.7] Add get Forecast Tunes Stats to Nitro routes for ForecastTunes

HyperAPI/hdp_api/README.md, HyperAPI/hdp_api/base/README.md, HyperAPI/hdp_api/base/router.py, HyperAPI/hdp_api/routes/correlations.py, README.md, build_requirements.txt, changelog.md, codebuild_build.yml, codebuild_test.yml, requirements.txt
- Update doc
- the buildspec file has been split into 2 separate files : 
- codebuild_build.yml : generate doc, build and publish package 
- codebuild_test.yml : linter and unit test for API
- Requirements have been split into package and build requirements.
=> [6.0.2] Split codebuild definitions into build and tests + incremental doc update

HyperAPI/hdp_api/routes/nitro.py, changelog.md, tests/data/schema_json/hdp_4.2.2.json
- Adding Route `getForecastTunesMetadata`
- Available since HDP 4.2.2
- POST `/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/tunes/metadata`
- Adding Route `getForecastTunesModalities`
- Available since HDP 4.2.2
- POST `/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/tunes/modalities`
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/projects/hyperapi_build/build/hyperapi_build:a3975c22-97c7-478f-8254-10fd639630d9/log?region=eu-central-1
=> [6.0.4]: Add 2 new Nitro routes (metadata & modalities)

HyperAPI/sessionClass.py, changelog.md
- Add new parameter to api call signature to get the raw response
- api.System.about(raw_response=True)
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/projects/hyperapi_build/build/hyperapi_build:a3975c22-97c7-478f-8254-10fd639630d9/log?region=eu-central-1
=> [6.0.6]: Add new parameter to api call signature to get the raw response

HyperAPI/hdp_api/routes/nitro.py, changelog.md, tests/data/schema_json/hdp_4.2.3.json
- Adding Route `getForecastMetadata`
- Available since HDP 4.2.3
- GET `/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/metadata`
- Deprecated route `getForecastTunesMetadata`
- Starting from HDP 4.2.3
- Superseded by `getForecastMetadata`
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/projects/hyperapi_build/build/hyperapi_build%3A8b6575e3-7d22-43dd-83bc-4e745fdb6ca3/log?region=eu-central-1
=> [6.0.7]: change the getForecastTunesMetadata for getForecastMetadata

HyperAPI/hyper_api/model.py
Erratum: the method created to get the file suffix for exporting models was into the Classifier class and not into the most general Model class, causing Regressors to fail.
=> [6.0.8] Put extract suffix method into general class

HyperAPI/hyper_api/model.py
Could not call method _extract_exportfile_suffix:
- it started with '__'
- should call super() instead of self.
=> [6.0.8] Call parent method with super()

HyperAPI/hdp_api/routes/auxdata.py, changelog.md
- Adding Route `getAuxDataModalities`
- Available since HDP 4.2.4
- GET `/projects/{project_ID}/auxdata/modalities/query`
=> [6.0.9] Add getAuxDataModalities route

HyperAPI/hdp_api/routes/auxdata.py, changelog.md
Added the following route, to update auxdata with new values:
```
class _updateAuxDataModalities(Route):
name = "updateAuxDataModalities"
httpMethod = Route.POST
available_since = "4.2.4"
path = "/projects/{project_ID}/auxdata/modalities/update"
_path_keys = {
'project_ID': Route.VALIDATOR_OBJECTID,
}
```
Link to the build:
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/projects/hyperapi_test/build/hyperapi_test%3Aa4cc8424-8bc8-4310-b8d5-131a4c05f4f7/log
=> [6.0.10] Add auxdata update route

HyperAPI/hdp_api/routes/nitro.py, changelog.md
- Adding Route `getForecastIdMetadata`
- Available since HDP 4.2.8
- GET `/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/metadata`
- Deprecated route `getForecastMetadata`
- Starting from HDP 4.2.8
- Superseded by `getForecastIdMetadata`
https://eu-central-1.console.aws.amazon.com/codesuite/codebuild/projects/hyperapi_build/build/hyperapi_build%3A88fa5df4-0b43-4d24-9978-e87bc7129654/log?region=eu-central-1
=> [7.0.3] - [NITRO]: change the getForecastTunesMetadata for getForecastMetadata 

HyperAPI/hdp_api/routes/nitro.py, changelog.md
put the code from branch Nitro 2.5 to master (https://github.com/HyperCube/HyperAPI/pull/113)
No change of version but a temporary version : 7.0.6.nitro
- Adding Route `getForecastIdMetadata`
- Available since HDP 4.2.9
- GET `/nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/metadata`
- Deprecated route `getForecastMetadata`
- Starting from HDP 4.2.9
- Superseded by `getForecastIdMetadata`
=> [7.0.3][7.0.6.nitro]: merge Nitro 2 5 in master

HyperAPI/hdp_api/routes/nitro.py, changelog.md
7.0.9
Adding Route getPosRecurrences and updatePosRecurrence
- Adding Route `getPosRecurrences`
- Available since HDP 4.2.10
- POST `/nitro/projects/{project_ID}/datasets/{dataset_ID}/pos/recurrences`
- Adding Route `updatePosRecurrence`
- Available since HDP 4.2.10
- POST `/nitro/projects/{project_ID}/datasets/{dataset_ID}/pos/{pos_ID}/recurrences`
=> [Nitro 2.6] add getPosRecurrence and updatePosRecurrence api

changelog.md
7.0.10
Adding Route getPosRecurrences and updatePosRecurrence
Adding Route getPosRecurrences
Available since HDP 4.2.10
POST /nitro/projects/{project_ID}/datasets/{dataset_ID}/pos/recurrences
Adding Route updatePosRecurrence
Available since HDP 4.2.10
POST /nitro/projects/{project_ID}/datasets/{dataset_ID}/pos/{pos_ID}/recurrences
=> 7.0.10 fix version Adding Route getPosRecurrences and updatePosRecurrence

HyperAPI/hyper_api/variable.py, changelog.md
Note that a test assertion should be added in API tests in Hypercube sources
A package has been generated: HyperAPI 7.0.11
but it was then deleted from pypi because it was failing when trying to get the list of projects on local
~\AppData\Roaming\Python\Python36\site-packages\HyperAPI\hyper_api\project.py in is_default(self)
226         """
227         if self.__api.session.version >= self.__api.session.version.__class__('3.6'):
--> 228             defaultProjectId = self.__api.Settings._getusersettings().get('defaultProjectId')
229         else:
230             defaultProjectId = self.__api.Projects.projects().get('defaultProject')
AttributeError: 'Settings' object has no attribute '_getusersettings'
=> [master] fix keep variable
