bearingpoint/bbs-hypercube-api

hyper_api/xray.py, hyper_api/xrayvariable.py
enable to create Xray on multiple targets
removed contrast_rate_value property
now, contrast_rate is read this way:
sort xray variables now takes as input parameter the variable associated to the contrast rate
=> creation of xray on multiple targets

hyper_api/ruleset.py
Define an additionnal kpi:
Define the target:
Create the ruleset:
=> handle more score types on target and additionnal kpis

hyper_api/dataset.py, hyper_api/model.py, hyper_api/project.py, hyper_api/rule.py, hyper_api/ruleset.py, hyper_api/target.py, hyper_api/variable.py, hyper_api/xray.py, hyper_api/xrayvariable.py
HyperAPI Documentation will be partially generated from docStrings:
Correction for predict_from_ruleset
=> Update of docStrings

sessionClass.py
Remove warnings on Api initialization:
=> Ignore urllib3 warning

README.md, buildspec.yml, docs/generate_doc.sh, requirements.txt, scripts/deploy.py
- Added source code archive step
- Added doc generate
- Update of README with quick installation steps for MACOS/Linux
=> [Codebuild]: Added build/deploy pipeline

hyper_api/index.rst, hyper_api/ruleset.py
Corrections:
- printing rulesets in errors is no more failing
- deleting rulesets in errors works now as expected
=> handle Rulesets in error

hdp_api/routes/nitro.py
Add a new route
Change a route path
Change routes method
=> Add/Update Routes

buildspec.yml, dist/Dockerfile, requirements.txt
- added numpy
- removed sklearn/scipy/xgboost dependencies
- added new docker image build step for CodeBuild
=> [CodeBuild]: Added docker image build pipeline

HyperAPI/__init__.py, HyperAPI/hdp_api/routes/nitro.py, buildspec.yml, dist/Dockerfile, setup.py
- Update Nitro API version to 1
- Add route updateForecastCoef : 
`POST : /nitro/projects/{project_ID}/datasets/{dataset_ID}/forecasts/{forecast_ID}/tunes/updatecoef`
=> Add New Nitro Route

HyperAPI/__init__.py, buildspec.yml, dist/Dockerfile, setup.py
update API to v2 to reflect changes.
Changes: route to export the result of the import of CSV file was added.
=> [Nitro] update API to v2 

setup.py
Removed import of __version__, which crashed the tests
=> Removed crashing import

HyperAPI/hdp_api/__init__.py, HyperAPI/hdp_api/routes/__init__.py, HyperAPI/hdp_api/routes/base/resource_base.py
the available since wasn't working as intended
=> Fix available since

HyperAPI/hdp_api/routes/dashboards.py, HyperAPI/hdp_api/routes/visualization.py, package_metadata.json
We need to make dashboard from a project with no dataset provided
=> Add dashboard routes from project only (and for visualization)

HyperAPI/hdp_api/_router.py, HyperAPI/hdp_api/routes/thirdParties.py, buildspec.yml, dist/Dockerfile
added new superset router class
=> [Superset Integration] Added 3rdparties routes

HyperAPI/hdp_api/_router.py, HyperAPI/hdp_api/routes/realTime.py, changelog.md
=> [5.1.10] Add RealTimeSocket new route

HyperAPI/hyper_api/variable.py
update metadata call Api arguments
=> update metadata call api arguments

HyperAPI/hdp_api/routes/realTime.py, HyperAPI/utils/version.py, changelog.md
- Add available_since for RealTime route
- Backport 4.2 version handling for patch versions of hdp
=> [5.1.10] Fix version management and RealTime availability

hyperapi.yml, scripts/deploy.py
- new pipeline for DEV account (HyperAPI)
=> codebuild: new pipeline

HyperAPI/hdp_api/routes/datasets.py, HyperAPI/hdp_api/routes/nitro.py, HyperAPI/hdp_api/routes/prediction.py, HyperAPI/hdp_api/routes/variable.py, HyperAPI/utils/version.py, buildspec.yml, dist/Dockerfile
Change pip server to s3.eu-central-1.amazonaws.com/pypi.hcube.cool
=> [4.2] Update version to 4.2 + change server

HyperAPI/hdp_api/routes/datasets.py, changelog.md
**_### Add post default dataset resampling endpoint_**
=> [5.1.11] Add post default dataset resampling endpoint

HyperAPI/hdp_api/routes/datasets.py, HyperAPI/hyper_api/variable.py
=> Fix default resampling

HyperAPI/hyper_api/variable.py
I still believe the route should return the variable after being updated
=> fix ignored status of a variable

HyperAPI/hyper_api/variable.py, changelog.md
Fix update metadata switch version
=> Fix update metadata switch version

HyperAPI/hdp_api/base/router.py, HyperAPI/hdp_api/routes/iot.py, changelog.md
Added new routes in order to drive the IoT ETL API (API GATEWAY) through HDP 4.1.
=> 6.0.1: added iotETLApi routes

HyperAPI/hyper_api/model.py, changelog.md
getexportscores route expects to receive only the suffix of the file to export.
=> [6.0.8] Fix BUG # 8996 Export model scores

HyperAPI/hdp_api/routes/datasets.py, changelog.md
Adding a route to export xsl files, the file format will be passed as a request parameter (if we need other formats in the future) : 
AB#9316
=> 6.0.11 Adding xls dataset export route

HyperAPI/hdp_api/base/router.py, HyperAPI/hdp_api/routes/admin.py, changelog.md, tests/data/schema_json/hdp_4.2.5.json
```
class _getUserWorksOverrides(Route):
name = "getUserWorksOverrides"
httpMethod = Route.GET
path = "/admin/user/{user_ID}/overrides"
_path_keys = {
'user_ID': Route.VALIDATOR_OBJECTID
}
```
=> 7.0 & 7.0.1: added getUserWorksOverrides route

HyperAPI/hyper_api/model.py, changelog.md
The perceptron is added to the API.
=> Perceptron added to the HyperCube API

HyperAPI/hdp_api/base/router.py, HyperAPI/hyper_api/dataset.py, HyperAPI/hyper_api/model.py, changelog.md
See PR: https://github.com/HyperCube/HyperAPI/pull/124
rebased work of @WassimAbida
=> [7.0.9]: TSForecaster model added + delimiter fix bug

HyperAPI/hyper_api/project.py, HyperAPI/hyper_api/ruleset.py, codebuild_test.yml
- project.userName property
- project.set_as_default method
- ruleset.getRules method
=> fix for HyperCube 4.4

HyperAPI/hyper_api/dataset.py, HyperAPI/hyper_api/model.py, HyperAPI/hyper_api/project.py, HyperAPI/hyper_api/ruleset.py, HyperAPI/hyper_api/xrayvariable.py
project:
- removed parameters related to demo project in create method
- not anymore default after deleting default
- removed user_id, share_users, share_users_ids, share_with_user
dataset:
- not anymore default after deleting default
- fixed set_as_default and is_default
- set as private get_discreteDict
xrayvariable:
- renamed get_by_id into get_by_column_id
ruleset:
- fixed delete, that was not always indicating that ruleset has been deleted
model:
- set as private create_TimeSeriesForecaster
=> [master] more fix for HC 4.4

HyperAPI/hyper_api/dataset.py, HyperAPI/hyper_api/index.rst, HyperAPI/hyper_api/ruleset.py, HyperAPI/hyper_api/xrayvariable.py, README.md, codebuild_build.yml, dist/Dockerfile, docs/conf.py
- Reorganize HyperAPI documentation. Add links between code examples and method documentation
https://s3.eu-central-1.amazonaws.com/hyperapi.hcube.cool/v8.0.2/index.html
- Fix Ruleset.minimize (to send only kpis that have been calculated on the ruleset). Raise an error when kpi is continuous
=> [master] fix bug Ruleset minimize
